apiVersion: v1
kind: Plugin
metadata:
  author: sheetung
  name: TaskTimer
  repository: ''
  version: 0.1.0
  description:
    en_US: 定时触发任务脚本
    zh_Hans: 定时触发任务脚本
  label:
    en_US: TaskTimer
    zh_Hans: TaskTimer
  icon: assets/icon.svg
spec:
  config: []
  components:
    EventListener:
      fromDirs:
      - path: components/event_listener/
execution:
  python:
    path: main.py
    attr: TaskTimer
